name: Add Enrollment Group
on:
  workflow_dispatch:
    inputs:
      dps_name:  
        description: 'DPS Name'
        required: true
        default: 'amdparetodemoDPS27'
      iot_hub_name:
        description: 'IOT Hub Name'
        required: true
        default: 'amdparetodemoIOTHub27'
      enrollment_group_name:
        description: 'Enrollment Group Name'
        required: true
        default: 'pareto-anywhere-eg'

# Environment Variables
env:
  HUB_Config-dpsName: "Pareto-Deployment-Service"

jobs:
  device-deployment-support:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CLUSTER_SERVICE_PRINCIPAL }}

    - name: Install az cli 
      uses: ./.github/actions/install-az-cli

    - name: Set default subscription
      run: az account set --subscription ${{secrets.SUBSCRIPTION_ID}}

    # Create Device Provisioning Service Enrollment Group
    - name: Create Device Provisioning Service Enrollment Group
      shell: bash
      run: |
        az iot dps enrollment-group create --dps-name ${{ github.event.inputs.dps_name }} --resource-group ${{ secrets.RESOURCE_GROUP}} --enrollment-id ${{ github.event.inputs.enrollment_group_name }} --auth-type key
    
    - name: Print Device Connection data
      shell: bash
      run: |
        echo "Primary Key: $(az iot dps enrollment-group show --dps-name ${{ github.event.inputs.dps_name }} --resource-group ${{ secrets.RESOURCE_GROUP}} --enrollment-id ${{ github.event.inputs.enrollment_group_name }} --keys true --query attestation.symmetricKey.primaryKey -o tsv)"
        echo "ID Scope: $(az iot dps show --name ${{ github.event.inputs.dps_name }} --resource-group ${{ secrets.RESOURCE_GROUP}} --query properties.idScope -o tsv)"