name: Azure Pareto ARM Deployment - Resources
on:
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CLUSTER_SERVICE_PRINCIPAL }}

    # Deploy ARM template
    # https://github.com/marketplace/actions/deploy-azure-resource-manager-arm-template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      id: deploy
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        template: ./deployments/supporting_resources_template.json
        parameters: ./deployments/supporting_resources_parameters.json

    # output variables from template
    - name: Print the outputs
      shell: bash
      run: |
        echo "iot hub name = " ${{ steps.deploy.outputs.iot_hub }}
        echo "event hub name = " ${{ steps.deploy.outputs.event_hub_name }}
        echo "webpubsub name = " ${{ steps.deploy.outputs.web_pub_sub_name }}