name: Deploy IoT Hub and DPS
on:
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CLUSTER_SERVICE_PRINCIPAL }}

    # Deploy ARM template
    # https://github.com/marketplace/actions/deploy-azure-resource-manager-arm-template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      id: deployIoT
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        template: ./deployments/device_template.json
        parameters: ./deployments/device_parameters.json
